# Location of Twig templates
slimTemplateDir: ../templates

# Slim Middleware that should be activated
slimMiddlewareObjects:
  - \USF\auth\SlimAuthMiddleware

# Slim Configuration
slimSettings:
  log.enabled: true
  log.monolog: true
  log.file_location: ../logs/application.log
  # Use Twig for templating
  view.twig: true
  # Rebuild views whenever they change
  view.twig.auto_reload: true
  # Ignore invalid variables instead of throwing an exception
  view.twig.strict_variables: false
  # Auto escape HTML data
  view.twig.autoescape: true
  # Use CAS for authentication
  casConfig:
    environment: development
  # AuthN/AuthZ Map
  # List URL patterns from most to least specific
  interceptUrlMap:
    GET:
      '/denied': # Use an exact match
        authN: denyAll
        authZ: denyAll
      '^.*': # Use RegEx to match all URLs
        authN: CAS
        authZ: permitAll
    POST:
      '/sample/**': # Use an Ant Pattern
        authN: denyAll
        authZ: denyAll
    PUT:
      '/**':
        authN: denyAll
        authZ: denyAll
    DELETE:
      '/**':
        authN: denyAll
        authZ: denyAll
